CREATE TABLE runtime_profiles (id TEXT NOT NULL, version INTEGER NOT NULL, name TEXT NOT NULL, sandbox_strength TEXT NOT NULL, default_actions_json TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'ACTIVE', PRIMARY KEY(id,version));
INSERT INTO runtime_profiles VALUES
('local-windows',1,'Local Windows agent','restricted','["repository-read","build","test"]','ACTIVE'),
('unix-agent',1,'Linux / macOS agent','restricted','["repository-read","build","test"]','ACTIVE'),
('docker-sandbox',1,'Docker sandbox','isolated','["repository-read","build","test"]','ACTIVE'),
('vps',1,'VPS','remote-isolated','["repository-read","deploy-staging"]','ACTIVE'),
('private-server',1,'Private server','private-isolated','["repository-read","deploy-staging"]','ACTIVE'),
('cloud-worker',1,'Cloud worker','edge-isolated','["worker-test","deploy-staging"]','ACTIVE'),
('network-agent',1,'Authorized network agent','read-only','["network-read"]','ACTIVE');

CREATE TABLE runtime_enrollment_challenges (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, workspace_id TEXT NOT NULL, runtime_type TEXT NOT NULL, display_name TEXT NOT NULL, code_hash TEXT NOT NULL, expires_at TEXT NOT NULL, consumed_at TEXT, actor_user_id INTEGER NOT NULL, correlation_id TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_runtime_challenge_scope ON runtime_enrollment_challenges(organization_id,workspace_id,expires_at);
CREATE TABLE runtime_identities (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, workspace_id TEXT NOT NULL, profile_id TEXT NOT NULL, profile_version INTEGER NOT NULL, display_name TEXT NOT NULL, credential_hash TEXT NOT NULL UNIQUE, state TEXT NOT NULL DEFAULT 'DISCONNECTED', capability_version INTEGER NOT NULL DEFAULT 1, enrolled_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, last_heartbeat_at TEXT, suspended_at TEXT, revoked_at TEXT, revocation_reason TEXT, actor_user_id INTEGER NOT NULL, correlation_id TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_runtime_identity_scope ON runtime_identities(organization_id,workspace_id,state);
CREATE TABLE runtime_capability_manifests (id TEXT PRIMARY KEY, runtime_id TEXT NOT NULL, organization_id TEXT NOT NULL, workspace_id TEXT NOT NULL, version INTEGER NOT NULL, platform TEXT NOT NULL, workspace_roots_json TEXT NOT NULL, actions_json TEXT NOT NULL, network_policy_json TEXT NOT NULL, resource_ceilings_json TEXT NOT NULL, secret_providers_json TEXT NOT NULL, sandbox_strength TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'ACCEPTED', evidence_refs TEXT NOT NULL DEFAULT '[]', correlation_id TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(runtime_id,version));
CREATE TABLE runtime_heartbeats (id TEXT PRIMARY KEY, runtime_id TEXT NOT NULL, organization_id TEXT NOT NULL, workspace_id TEXT NOT NULL, health TEXT NOT NULL, capability_version INTEGER NOT NULL, metrics_json TEXT NOT NULL, nonce TEXT NOT NULL, correlation_id TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(runtime_id,nonce));
CREATE TABLE runtime_execution_leases (id TEXT PRIMARY KEY, runtime_id TEXT NOT NULL, contract_id TEXT NOT NULL, organization_id TEXT NOT NULL, workspace_id TEXT NOT NULL, task_id TEXT NOT NULL, plan_version INTEGER NOT NULL, action TEXT NOT NULL, workspace_roots_json TEXT NOT NULL, network_policy_json TEXT NOT NULL, budget_json TEXT NOT NULL, evidence_requirements TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'ISSUED', expires_at TEXT NOT NULL, cancelled_at TEXT, cancellation_reason TEXT, actor_user_id INTEGER NOT NULL, correlation_id TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_runtime_lease_scope ON runtime_execution_leases(runtime_id,workspace_id,status,expires_at);
CREATE TABLE runtime_lease_events (id TEXT PRIMARY KEY, lease_id TEXT NOT NULL, runtime_id TEXT NOT NULL, organization_id TEXT NOT NULL, workspace_id TEXT NOT NULL, event_type TEXT NOT NULL, reason TEXT NOT NULL, actor TEXT NOT NULL, correlation_id TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE runtime_evidence_reports (id TEXT PRIMARY KEY, lease_id TEXT NOT NULL, runtime_id TEXT NOT NULL, organization_id TEXT NOT NULL, workspace_id TEXT NOT NULL, outcome TEXT NOT NULL, evidence_refs TEXT NOT NULL, summary TEXT NOT NULL, correlation_id TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE runtime_revocations (id TEXT PRIMARY KEY, runtime_id TEXT NOT NULL, organization_id TEXT NOT NULL, workspace_id TEXT NOT NULL, reason TEXT NOT NULL, evidence_refs TEXT NOT NULL, actor_user_id INTEGER NOT NULL, correlation_id TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE runtime_emergency_stops (id TEXT PRIMARY KEY, organization_id TEXT NOT NULL, workspace_id TEXT NOT NULL, reason TEXT NOT NULL, evidence_refs TEXT NOT NULL, cancelled_leases INTEGER NOT NULL, suspended_runtimes INTEGER NOT NULL, actor_user_id INTEGER NOT NULL, correlation_id TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
