import { sha256, randomHex } from './security'
import { workspaceFromRequest } from './task-engine'

interface Env { DB: D1Database }
const json=(v:unknown,s=200)=>Response.json(v,{status:s,headers:{'Cache-Control':'no-store'}}), fail=(m:string,s=400)=>json({error:m},s)
const uid=()=>crypto.randomUUID().replaceAll('-','').slice(0,16), org=(a:number)=>`owner-${a}`
const body=async<T>(r:Request)=>{if(!r.headers.get('content-type')?.includes('application/json'))throw fail('JSON request required',415);return r.json<T>()}
const text=(v:unknown,n:string,min=1,max=5000)=>{if(typeof v!=='string'||v.trim().length<min||v.trim().length>max)throw fail(`${n} must contain ${min} to ${max} characters`,422);return v.trim()}
const strings=(v:unknown,n:string,max=50)=>{if(!Array.isArray(v)||v.length>max||v.some(x=>typeof x!=='string'||x.length>240))throw fail(`${n} must be a bounded string array`,422);return [...new Set(v)] as string[]}
const bearer=(r:Request)=>r.headers.get('authorization')?.match(/^Bearer ([A-Za-z0-9]+)$/)?.[1]

async function runtimeAuth(request:Request,env:Env){const token=bearer(request);if(!token)throw fail('Runtime credential required',401);const row=await env.DB.prepare("SELECT * FROM runtime_identities WHERE credential_hash=? AND state NOT IN ('REVOKED','SUSPENDED')").bind(await sha256(token)).first<Record<string,unknown>>();if(!row)throw fail('Invalid or inactive runtime credential',401);return row}
export async function handleRuntimeAgentApi(request:Request,env:Env,correlation:string):Promise<Response|null>{
 const url=new URL(request.url), method=request.method;if(!url.pathname.startsWith('/api/runtime-agent/'))return null
 if(url.pathname==='/api/runtime-agent/enroll'&&method==='POST'){
  const input=await body<{challenge_id:string;code:string;platform:string;workspace_roots:string[];actions:string[];network_policy:unknown;resource_ceilings:unknown;secret_providers:string[];sandbox_strength:string;evidence_refs?:string[]}>(request)
  const challenge=await env.DB.prepare("SELECT * FROM runtime_enrollment_challenges WHERE id=? AND consumed_at IS NULL AND expires_at>CURRENT_TIMESTAMP").bind(text(input.challenge_id,'Challenge ID')).first<Record<string,unknown>>()
  if(!challenge||await sha256(text(input.code,'Pairing code'))!==challenge.code_hash)throw fail('Invalid or expired enrollment challenge',401)
  const profile=await env.DB.prepare("SELECT * FROM runtime_profiles WHERE id=? AND status='ACTIVE' ORDER BY version DESC LIMIT 1").bind(challenge.runtime_type).first<Record<string,unknown>>();if(!profile)throw fail('Runtime profile unavailable',422)
  const actions=strings(input.actions,'Actions'),allowed=JSON.parse(String(profile.default_actions_json)) as string[];if(actions.some(x=>!allowed.includes(x)))throw fail('Capability manifest exceeds the runtime profile',403)
  const roots=strings(input.workspace_roots,'Workspace roots');if(!roots.length)throw fail('At least one workspace root is required',422)
  const id=uid(),credential=randomHex(32),manifest=uid()
  await env.DB.batch([
   env.DB.prepare('UPDATE runtime_enrollment_challenges SET consumed_at=CURRENT_TIMESTAMP WHERE id=? AND consumed_at IS NULL').bind(challenge.id),
   env.DB.prepare("INSERT INTO runtime_identities(id,organization_id,workspace_id,profile_id,profile_version,display_name,credential_hash,state,actor_user_id,correlation_id) VALUES(?,?,?,?,?,?,?,'DISCONNECTED',?,?)").bind(id,challenge.organization_id,challenge.workspace_id,profile.id,profile.version,challenge.display_name,await sha256(credential),challenge.actor_user_id,correlation),
   env.DB.prepare('INSERT INTO runtime_capability_manifests(id,runtime_id,organization_id,workspace_id,version,platform,workspace_roots_json,actions_json,network_policy_json,resource_ceilings_json,secret_providers_json,sandbox_strength,evidence_refs,correlation_id) VALUES(?,?,?,?,1,?,?,?,?,?,?,?,?,?)').bind(manifest,id,challenge.organization_id,challenge.workspace_id,text(input.platform,'Platform'),JSON.stringify(roots),JSON.stringify(actions),JSON.stringify(input.network_policy??{}),JSON.stringify(input.resource_ceilings??{}),JSON.stringify(strings(input.secret_providers,'Secret providers')),text(input.sandbox_strength,'Sandbox strength'),JSON.stringify(strings(input.evidence_refs||[],'Evidence')),correlation)
  ]);return json({runtime_id:id,credential,credential_returned_once:true,state:'DISCONNECTED'},201)
 }
 const runtime=await runtimeAuth(request,env)
 if(url.pathname==='/api/runtime-agent/heartbeat'&&method==='POST'){
  const input=await body<{nonce:string;health:string;capability_version:number;metrics?:unknown}>(request);if(Number(input.capability_version)!==Number(runtime.capability_version))throw fail('Capability manifest version mismatch',409)
  const id=uid();try{await env.DB.batch([env.DB.prepare('INSERT INTO runtime_heartbeats(id,runtime_id,organization_id,workspace_id,health,capability_version,metrics_json,nonce,correlation_id) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,runtime.id,runtime.organization_id,runtime.workspace_id,text(input.health,'Health'),input.capability_version,JSON.stringify(input.metrics??{}),text(input.nonce,'Nonce'),correlation),env.DB.prepare("UPDATE runtime_identities SET state=?,last_heartbeat_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(input.health==='healthy'?'CONNECTED':'DEGRADED',runtime.id)]);return json({ok:true,heartbeat_id:id})}catch{return json({ok:true,idempotent:true})}
 }
 if(url.pathname==='/api/runtime-agent/leases'&&method==='GET'){const rows=await env.DB.prepare("SELECT * FROM runtime_execution_leases WHERE runtime_id=? AND status='ISSUED' AND expires_at>CURRENT_TIMESTAMP ORDER BY created_at").bind(runtime.id).all();return json({leases:rows.results})}
 const result=url.pathname.match(/^\/api\/runtime-agent\/leases\/([a-f0-9]{16})\/result$/)
 if(result&&method==='POST'){const input=await body<{outcome:string;summary:string;evidence_refs:string[]}>(request), evidence=strings(input.evidence_refs,'Evidence');if(!evidence.length)throw fail('Runtime evidence is required',422);const lease=await env.DB.prepare("SELECT * FROM runtime_execution_leases WHERE id=? AND runtime_id=? AND status='ISSUED' AND expires_at>CURRENT_TIMESTAMP").bind(result[1],runtime.id).first<Record<string,unknown>>();if(!lease)throw fail('Active runtime lease not found',404);const status=input.outcome==='succeeded'?'SUCCEEDED':'FAILED',id=uid();await env.DB.batch([env.DB.prepare('INSERT INTO runtime_evidence_reports(id,lease_id,runtime_id,organization_id,workspace_id,outcome,evidence_refs,summary,correlation_id) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,lease.id,runtime.id,runtime.organization_id,runtime.workspace_id,input.outcome,JSON.stringify(evidence),text(input.summary,'Summary',3),correlation),env.DB.prepare('UPDATE runtime_execution_leases SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(status,lease.id),env.DB.prepare('INSERT INTO runtime_lease_events(id,lease_id,runtime_id,organization_id,workspace_id,event_type,reason,actor,correlation_id) VALUES(?,?,?,?,?,?,?,?,?)').bind(uid(),lease.id,runtime.id,runtime.organization_id,runtime.workspace_id,status,input.outcome,`runtime:${runtime.id}`,correlation)]);return json({evidence_id:id,status})}
 return fail('Runtime agent route not found',404)
}

export async function handleRuntimeApi(request:Request,env:Env,actor:number,correlation:string):Promise<Response|null>{
 const url=new URL(request.url),method=request.method;if(!url.pathname.startsWith('/api/runtimes'))return null;const workspace=workspaceFromRequest(request,actor),organization=org(actor)
 if(url.pathname==='/api/runtimes'&&method==='GET'){const [profiles,identities,leases,stops]=await Promise.all([env.DB.prepare("SELECT * FROM runtime_profiles WHERE status='ACTIVE' ORDER BY name").all(),env.DB.prepare('SELECT id,profile_id,profile_version,display_name,state,capability_version,enrolled_at,last_heartbeat_at,suspended_at,revoked_at FROM runtime_identities WHERE organization_id=? AND workspace_id=? ORDER BY enrolled_at DESC').bind(organization,workspace).all(),env.DB.prepare('SELECT * FROM runtime_execution_leases WHERE organization_id=? AND workspace_id=? ORDER BY created_at DESC LIMIT 100').bind(organization,workspace).all(),env.DB.prepare('SELECT * FROM runtime_emergency_stops WHERE organization_id=? AND workspace_id=? ORDER BY created_at DESC LIMIT 20').bind(organization,workspace).all()]);return json({profiles:profiles.results,runtimes:identities.results,leases:leases.results,emergency_stops:stops.results,heartbeat_fresh_seconds:90})}
 if(url.pathname==='/api/runtimes/enrollment-challenges'&&method==='POST'){const input=await body<{runtime_type:string;display_name:string;ttl_minutes?:number}>(request),profile=await env.DB.prepare("SELECT id FROM runtime_profiles WHERE id=? AND status='ACTIVE'").bind(text(input.runtime_type,'Runtime type')).first();if(!profile)throw fail('Unknown runtime profile',422);const id=uid(),code=randomHex(6),expires=new Date(Date.now()+Math.max(5,Math.min(Number(input.ttl_minutes||10),30))*60000).toISOString();await env.DB.prepare('INSERT INTO runtime_enrollment_challenges(id,organization_id,workspace_id,runtime_type,display_name,code_hash,expires_at,actor_user_id,correlation_id) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,organization,workspace,input.runtime_type,text(input.display_name,'Display name'),await sha256(code),expires,actor,correlation).run();return json({challenge_id:id,pairing_code:code,expires_at:expires,pairing_code_returned_once:true},201)}
 if(url.pathname==='/api/runtimes/leases'&&method==='POST'){const input=await body<{runtime_id:string;contract_id:string;action:string;ttl_minutes?:number}>(request),runtime=await env.DB.prepare("SELECT i.*,m.workspace_roots_json,m.actions_json,m.network_policy_json,m.resource_ceilings_json FROM runtime_identities i JOIN runtime_capability_manifests m ON m.runtime_id=i.id AND m.version=i.capability_version WHERE i.id=? AND i.organization_id=? AND i.workspace_id=? AND i.state='CONNECTED' AND i.last_heartbeat_at>datetime('now','-90 seconds') AND m.status='ACCEPTED'").bind(input.runtime_id,organization,workspace).first<Record<string,unknown>>();if(!runtime)throw fail('A live verified runtime is required',409);const contract=await env.DB.prepare("SELECT c.*,g.runtimes_json FROM specialist_execution_contracts c JOIN specialist_capability_grants g ON g.id=c.grant_id WHERE c.id=? AND c.organization_id=? AND c.workspace_id=? AND c.status='READY' AND c.expires_at>CURRENT_TIMESTAMP AND g.status='ACTIVE'").bind(input.contract_id,organization,workspace).first<Record<string,unknown>>();if(!contract)throw fail('A current specialist execution contract is required',403);if(!(JSON.parse(String(runtime.actions_json)) as string[]).includes(input.action))throw fail('Action is outside the runtime capability manifest',403);if(!(JSON.parse(String(contract.runtimes_json)) as string[]).includes(String(runtime.profile_id)))throw fail('Runtime is outside the specialist capability grant',403);const id=uid(),expires=new Date(Date.now()+Math.max(1,Math.min(Number(input.ttl_minutes||10),60))*60000).toISOString();await env.DB.batch([env.DB.prepare("INSERT INTO runtime_execution_leases(id,runtime_id,contract_id,organization_id,workspace_id,task_id,plan_version,action,workspace_roots_json,network_policy_json,budget_json,evidence_requirements,status,expires_at,actor_user_id,correlation_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?, 'ISSUED',?,?,?)").bind(id,runtime.id,contract.id,organization,workspace,contract.task_id,contract.plan_version,input.action,runtime.workspace_roots_json,runtime.network_policy_json,runtime.resource_ceilings_json,contract.evidence_requirements,expires,actor,correlation),env.DB.prepare('INSERT INTO runtime_lease_events(id,lease_id,runtime_id,organization_id,workspace_id,event_type,reason,actor,correlation_id) VALUES(?,?,?,?,?,?,?,?,?)').bind(uid(),id,runtime.id,organization,workspace,'ISSUED','Owner issued bounded lease',`user:${actor}`,correlation)]);return json({lease_id:id,status:'ISSUED',expires_at:expires},201)}
 const revoke=url.pathname.match(/^\/api\/runtimes\/([a-f0-9]{16})\/revoke$/);if(revoke&&method==='POST'){const input=await body<{reason:string;evidence_refs:string[]}>(request),reason=text(input.reason,'Reason',3),evidence=strings(input.evidence_refs,'Evidence');if(!evidence.length)throw fail('Revocation evidence is required',422);const runtime=await env.DB.prepare('SELECT id FROM runtime_identities WHERE id=? AND organization_id=? AND workspace_id=?').bind(revoke[1],organization,workspace).first();if(!runtime)throw fail('Runtime not found',404);await env.DB.batch([env.DB.prepare("UPDATE runtime_identities SET state='REVOKED',revoked_at=CURRENT_TIMESTAMP,revocation_reason=?,credential_hash=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(reason,`revoked:${uid()}`,revoke[1]),env.DB.prepare("UPDATE runtime_execution_leases SET status='CANCELLED',cancelled_at=CURRENT_TIMESTAMP,cancellation_reason=?,updated_at=CURRENT_TIMESTAMP WHERE runtime_id=? AND status IN ('ISSUED','RUNNING')").bind(reason,revoke[1]),env.DB.prepare('INSERT INTO runtime_revocations(id,runtime_id,organization_id,workspace_id,reason,evidence_refs,actor_user_id,correlation_id) VALUES(?,?,?,?,?,?,?,?)').bind(uid(),revoke[1],organization,workspace,reason,JSON.stringify(evidence),actor,correlation)]);return json({ok:true,status:'REVOKED'})}
 if(url.pathname==='/api/runtimes/emergency-stop'&&method==='POST'){const input=await body<{reason:string;evidence_refs:string[]}>(request),reason=text(input.reason,'Reason',3),evidence=strings(input.evidence_refs,'Evidence');if(!evidence.length)throw fail('Emergency-stop evidence is required',422);const leases=await env.DB.prepare("UPDATE runtime_execution_leases SET status='CANCELLED',cancelled_at=CURRENT_TIMESTAMP,cancellation_reason=?,updated_at=CURRENT_TIMESTAMP WHERE organization_id=? AND workspace_id=? AND status IN ('ISSUED','RUNNING')").bind(reason,organization,workspace).run(),runtimes=await env.DB.prepare("UPDATE runtime_identities SET state='SUSPENDED',suspended_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE organization_id=? AND workspace_id=? AND state NOT IN ('REVOKED','SUSPENDED')").bind(organization,workspace).run(),id=uid();await env.DB.prepare('INSERT INTO runtime_emergency_stops(id,organization_id,workspace_id,reason,evidence_refs,cancelled_leases,suspended_runtimes,actor_user_id,correlation_id) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,organization,workspace,reason,JSON.stringify(evidence),leases.meta.changes,runtimes.meta.changes,actor,correlation).run();return json({id,status:'STOPPED',cancelled_leases:leases.meta.changes,suspended_runtimes:runtimes.meta.changes})}
 return fail('Runtime route not found',404)
}
